language: python
python:

  - "3.6"

install:
- pip install --upgrade pip
- pip install -r requirements.txt

- export PYTHONPATH=$PYTHONPATH:$(pwd)/main
- python3 setup.py install
# command to run tests
script:
# unit test
- python -m pytest -v
# linting test
- flake8