sudo: required
services:
- docker
language: python
python:

  - "3.6"

install:
- pip install --upgrade pip
- pip install -r requirements.txt

- export PYTHONPATH=$PYTHONPATH:$(pwd)/main

# command to run tests
script:
# unit test
- python -m pytest -v
# linting test

after_success:
- sh .travis/deploy_dockerhub.sh